feat: installing dependencies
project-zusammen/bookswap-frontend pull request #1
Opened 2023-12-24 04:07 UTC by anangyoga

2023-12-24 04:28 UTC, fatjan commented on README.md
> -1. Clone the repository
yg part ini boleh ga di remove ga?

2023-12-24 04:29 UTC, fatjan requested changes
Please update PR as per my request in the PR comment. Thank you

2023-12-24 04:45 UTC, anangyoga commented on README.md
> -1. Clone the repository
maaf kak @fatjan maksudnya gimana ya? "ga boleh diremove" atau mau dihapus aja, ya?

2023-12-24 06:10 UTC, anangyoga commented
hi kak @fatjan I have fixed the readme as per your request. thank you

2023-12-24 07:06 UTC, fatjan commented on README.md
> -    ```bash
kalau masih ada changes kaya gini berarti belum sama ya sama kondisi awalnya.

Ini kayanya kamu lupa kasih tab di awal line.

kalau sama kaya awalnya dia akan terlihat kaya line 1 - 7, no changes.

Buat skrang gapapa, aku approve. Next time kalau ada unnecessary changes tolong di revert. Thank you

2023-12-24 07:06 UTC, fatjan approved these changes

2023-12-25 00:22 UTC, fatjan commented on README.md
> -    ```bash
Feel free to merge the PR

2023-12-27 02:18 UTC, merged